insert into public.race("name"),VALUES
("doberman-dog"),
("pointer-dog"),
("dachshund-dog"),
("weimaraner dog"),
("siberian dog"),
("pitbull dog"),
("Bernese Montain dog"),
("great dane-dog"),
("bulldog-dog"),
("beagle-dog"),
("golden retriever-dog"),
("yorkshire-dog"),
("border colie-dog"),
("greyhound dog"),
("mongrel dog"),
("york chocolate cat"),
("siberian cat"),
("persian cat "),
("oriental cat "),
("siamese cat"),
("orange cat"),
("parrot"),
("monkey"),
("horse"),
("ferret"),
("hamster")